service: koinonia
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  profile: my
  versionFunctions: true
  memorySize: 512
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource: "*"
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeFunctionConfiguration
            - lambda:GetFunction
            - lambda:GetFunctionConfiguration
          Resource: "*"
        - Effect: Allow
          Action:
            - execute-api:Invoke
          Resource: "*"


package:
  individually: true

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}


